version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
  axon:
    image: axoniq/axonserver
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"
